### ISSUE TITLE
Agent server fails to handle `asyncio.CancelledError` from `create_kernels()`

### ISSUE THREAD

**Issue by rapsealk** [lablup/backend.ai#1128]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

b2c4a7a43a6910d8860025b98ce7b1eed43e90a2

### Describe the bug

The agent server fails to handle `asyncio.CancelledError` in some cases:
```sh
2023-03-06 11:07:07.884 ERROR callosum.rpc.channel.Peer [16442] RPC user error
Traceback (most recent call last):
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/dist/export/python/virtualenvs/python-default/3.11.2/lib/python3.11/site-packages/callosum/rpc/channel.py", line 281, in _func_task
    result = await self._func_scheduler.get_fut(server_request_id)
    ^^^^^^^^^^^^^^^^^
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/dist/export/python/virtualenvs/python-default/3.11.2/lib/python3.11/site-packages/callosum/ordering.py", line 224, in get_fut
    return await task
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/agent/server.py", line 158, in _inner
    return await meth(
    ^^^^^^^^^^^^^^^^^
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/agent/server.py", line 133, in _inner
    return await meth(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/agent/server.py", line 386, in create_kernels
    raw_results = [
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/agent/server.py", line 388, in <listcomp>
    "id": str(result["id"]),
    ^^^^^^^^^^^^^^^^^
TypeError: 'CancelledError' object is not subscriptable
```

`asyncio.CancelledError` has been a subclass of `BaseException` rather than `Exception` since Python 3.8. Therefore, it cannot be filtered by condition `filter(lambda item: isinstance(item, Exception))`.

https://github.com/lablup/backend.ai/blob/b2c4a7a43a6910d8860025b98ce7b1eed43e90a2/src/ai/backend/agent/server.py#L380

### Expected Behavior

Raises an exception and does not attempt to read values by index.

**Comment by achimnol** [comment]
That part of code has been refactored a long time ago, and all currently active releases should not have the particular line of this issue:
https://github.com/lablup/backend.ai/blame/main/src/ai/backend/agent/server.py#L454-L457
