### ISSUE TITLE
How to turn-on the session start button ?

### ISSUE THREAD

**Issue by ChaejinE** [lablup/backend.ai#1137]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

22.09.16

### Describe the bug

![image](https://user-images.githubusercontent.com/69780812/223363303-b53f63b0-1809-4d12-ba73-159fa42f6ba7.png)

i installed using your python pkg and hosted manager server, ui server.
but i cant use the bakcend.ai paltforom cause button above the picture.
please help me .. i wanna enjoy this platform.

**Comment by ChaejinE** [comment]
```
backend.ai mgr image rescan cr.backend.ai
```
- Is it because of the rescan part? => Error

```2023-03-07 09:45:47.566 ERROR ai.backend.manager.cli.image_impl [44500] An error occurred.
Traceback (most recent call last):
  File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/ai/backend/manager/cli/image_impl.py", line 183, in rescan_images
    await rescan_images_func(etcd, db, registry=registry)
  File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/ai/backend/manager/models/image.py", line 105, in rescan_images
    async with aiotools.TaskGroup() as tg:
  File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiotools/taskgroup/base_compat.py", line 189, in __aexit__
    raise me from None
aiotools.taskgroup.types.TaskGroupError: ('unhandled errors in a TaskGroup; 1 sub errors: (TaskGroupError)\n + TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (InvalidURL)\n + InvalidURL: harbor?scope=repository:stable/python-torch:pull&offline_token=true&client_id=docker&service=registry\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/ai/backend/manager/container_registry/base.py", line 144, in _scan_image\n |     rqst_args = await registry_login(\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/ai/backend/common/docker.py", line 157, in login\n |     async with sess.get(realm, params=params, auth=basic_auth) as resp:\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__\n |     self._resp = await self._coro\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiohttp/client.py", line 508, in _request\n |     req = self._request_class(\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__\n |     self.update_host(url)\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 364, in update_host\n |     raise InvalidURL(url)\n\n\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/ai/backend/manager/container_registry/base.py", line 91, in rescan_single_registry\n |     async with aiotools.TaskGroup() as tg:\n |   File "/home/bai/.pyenv/versions/3.10.10/envs/bai/lib/python3.10/site-packages/aiotools/taskgroup/base_compat.py", line 189, in __aexit__\n |     raise me from None\n\n',)
```

**Comment by ChaejinE** [comment]
[Solved] docker registry rescan
