### ISSUE TITLE
Trafaret validation errors are not compatible with unpickling for logging

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#158]
The pickle error happens when _unpickling_ the exception, so we loose the original context of the validation errors.

A sample error:
```
Exception in thread Logger:
Traceback (most recent call last):
  File "/Users/daniyar/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/daniyar/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/daniyar/Lablup/backend.ai/backend.ai-dev/common/src/ai/backend/common/logging.py", line 252, in log_worker
    rec = pickle.loads(data)
  File "/Users/daniyar/.pyenv/versions/3.8.1/envs/venv-4e16ujft-manager/lib/python3.8/site-packages/tblib/pickling_support.py", line 26, in unpickle_exception
    inst = func(*args)
  File "/Users/daniyar/.pyenv/versions/3.8.1/envs/venv-4e16ujft-manager/lib/python3.8/site-packages/trafaret/dataerror.py", line 23, in __init__
    raise RuntimeError('Only str or dict is supported, got %r' % error)
RuntimeError: Only str or dict is supported, got None
```

**Comment by achimnol** [comment]
Maybe related to Deepwalker/trafaret_forked#68
(FYI: The main repository maintained is [Deepwalker/trafaret](https://github.com/Deepwalker/trafaret) instead of trafaret_forked)

**Comment by achimnol** [comment]
I have figured out that this is a combination of the following issues:

1. `trafaret.DataError` is not unpicklable.
Adding the following code into it resolves the issue:
```python3
def __reduce__(self):
    return (type(self), (self.error, self.name, self.value, self.trafaret, self.code))
```

2. Some API handlers (notably, `session._create` and `session.create_from_template`) does not use `check_api_params` decorator which converts `trafaret.DataError` into (pickle-safe) `InvalidAPIParameters` but instead perform the validation inside their bodies to handle multiple client versions.
   We need to do the conversion in `exception_middleware`, in addition to `check_api_params`.

**Comment by LemieuxCF** [comment]
I see, thanks. Should this issue be prioritized?

**Comment by achimnol** [comment]
I'm trying to know which of `tblib` and `trafaret` should be fixed to get an ultimate resolution...
Just too annoying because it's intefering with reviewing other PRs.....

**Comment by LemieuxCF** [comment]
Gotcha, will start working on it on Monday
