### ISSUE TITLE
Mismatches in `error_logs` severity

### ISSUE THREAD

**Issue by rapsealk** [lablup/backend.ai#1949]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

9e56e5449acc8aefabcfa6aa4612b317bae9a2ec

### Describe the bug

It has been observed that the manager fails to insert a new `error_logs` row after #1924 and leaves error below:
(LogSeverity enum values has been updated from lowercases to uppercases.)
```sh
2024-03-05 09:34:48.374 ERROR aiohttp.server [20313] Error handling request
Traceback (most recent call last):
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
    ^^^^^^^^^^^^^^^^^
asyncpg.exceptions.InvalidTextRepresentationError: invalid input value for enum errorlog_severity: "ERROR"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
    ^^^^^^^^^^^^^^^^^
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.InvalidTextRepresentationError'>: invalid input value for enum errorlog_severity: "ERROR"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/src/ai/backend/manager/server.py", line 255, in exception_middleware
    await error_monitor.capture_exception()
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/src/ai/backend/common/plugin/monitor.py", line 87, in capture_exception
    await plugin_instance.capture_exception(exc_instance, context)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/src/ai/backend/manager/plugin/error_monitor.py", line 87, in capture_exception
    await conn.execute(query)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 453, in execute
    result = await greenlet_spawn(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
    ^^^^^^^^^^^^^^^^^
File "/Users/rapsealk/Desktop/git/backend.ai-dev2/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
    ^^^^^^^^^^^^^^^^^
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.InvalidTextRepresentationError'>: invalid input value for enum errorlog_severity: "ERROR"
[SQL: INSERT INTO error_logs (severity, source, "user", is_read, is_cleared, message, context_lang, context_env, traceback) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING error_logs.id]
[parameters: (<LogSeverity.ERROR: 'ERROR'>, 'manager', None, False, False, "ai.backend.manager.api.exceptions.VFolderNotFound: No such virtual folder.\n -> extra_data: 'aaa'", 'python', 'null', 'File "/Users/rapsealk/Desktop/git/backend.ai-dev2/src/ai/backend/manager/server.py", line 244, in exception_middleware\n    resp = await handler(requ ... (1610 characters truncated) ... rapsealk/Desktop/git/backend.ai-dev2/src/ai/backend/manager/api/vfolder.py", line 288, in _wrapped\n    raise VFolderNotFound(extra_data=folder_name)')]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
```

### To Reproduce

Attempt exceptional behavior - such as accessing non-existing VFolder.

**Comment by rapsealk** [comment]
This has been resolved by 6c3f056.
