### ISSUE TITLE
Storage-Proxy raises errors when performing folder-related actions with xfs backend

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#295]
Storage-Proxy does not work well with the `xfs` backend. Especially, the creation and deletion of a virtual folder raises errors.

## How to reproduce

* Check if the host machine uses xfs filesystem.
  <img width="870" alt="image" src="https://user-images.githubusercontent.com/7539358/136482192-7cf9d6da-caf1-44e0-a193-aa8904de833c.png">
* Configure the Storage-Proxy to use xfs backend:
```
# example config to use xfs as a Storage-Proxy backend
[volume.volume1]
backend = "xfs"
path = "/home/devops/vfroot/local"
```
* Try to create a virtual folder, which raises this error
```
INFO ManagerAPI::CREATE_VFOLDER(v:volume1, f:6b5233d3-041d-4bcd-ba8f-e88cffd49884)
ERROR Error handling request
Traceback (most recent call last):
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/api/manager.py", line 35, in token_auth_middleware
return await handler(request)
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/api/manager.py", line 104, in create_vfolder
await volume.create_vfolder(params["vfid"], params["options"])
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/xfs/__init__.py", line 97, in create_vfolder
if options is None or options.quota is None:  # max quota i.e. the whole fs size
AttributeError: 'dict' object has no attribute 'quota'
```
* Try to delete a virtual folder, which raises this error
```
Traceback (most recent call last):
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/home/devops/.pyenv/versions/storage-proxy-2103/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/api/manager.py", line 35, in token_auth_middleware
return await handler(request)
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/api/manager.py", line 121, in delete_vfolder
await volume.delete_vfolder(params["vfid"])
File "/home/devops/backend.ai-2103/storage-proxy/src/ai/backend/storage/xfs/__init__.py", line 123, in delete_vfolder
raise VFolderNotFoundError("VFolder with id {} does not exist".format(vfid))
ai.backend.storage.exception.VFolderNotFoundError: VFolder with id dcd9c470-1b7f-46d2-8bac-a64d2698e929 does not exist
```
* It works without problem if I change `backend` from `xfs` to `vfs`.

**Comment by lizable** [comment]
This issue will be resolved in [storage-proxy#13](https://github.com/lablup/backend.ai-storage-proxy/pull/13).
