### ISSUE TITLE
`resolve_image_distro()` attempt to create container before pulling image

### ISSUE THREAD

**Issue by jopemachine** [lablup/backend.ai#3123]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

main

### Describe the bug

The following error occurs on the agent.
This occurs because `resolve_image_distro()` attempts to create a container with an image that has not been pulled under certain conditions.

Note that `init_kernel_context()` is called before `pull_image()` in `create_kernel()`

To reproduce the error, refer to the "To reproduce" section below.

```
2024-11-20 06:32:35.392 ERROR ai.backend.agent.server [84388] unexpected error
Traceback (most recent call last):
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 169, in _inner
    return await meth(
           ^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 145, in _inner
    return await meth(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 579, in create_kernels
    raise errors[0]
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/agent.py", line 1834, in create_kernel
    ctx = await self.init_kernel_context(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/docker/agent.py", line 1551, in init_kernel_context
    distro = await self.resolve_image_distro(kernel_config["image"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/docker/agent.py", line 1327, in resolve_image_distro
    container = await docker.containers.create(container_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/containers.py", line 86, in create
    data = await self.docker._query_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 323, in _query_json
    async with self._query(
               ^^^^^^^^^^^^
  File "/home/jopemachine/.pyenv/versions/3.12.6/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 232, in _query
    yield await self._do_query(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 298, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
aiodocker.exceptions.DockerError: DockerError(404, 'No such image: 192.168.0.112/test-project/e3e32:0.2')
2024-11-20 06:32:35.393 ERROR callosum.rpc.channel.Peer [84388] RPC user error
Traceback (most recent call last):
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/callosum/rpc/channel.py", line 292, in _func_task
    result = await self._func_scheduler.get_fut(server_request_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/callosum/ordering.py", line 214, in get_fut
    return await task
           ^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 169, in _inner
    return await meth(
           ^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 145, in _inner
    return await meth(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/server.py", line 579, in create_kernels
    raise errors[0]
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/agent.py", line 1834, in create_kernel
    ctx = await self.init_kernel_context(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/docker/agent.py", line 1551, in init_kernel_context
    distro = await self.resolve_image_distro(kernel_config["image"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/src/ai/backend/agent/docker/agent.py", line 1327, in resolve_image_distro
    container = await docker.containers.create(container_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/containers.py", line 86, in create
    data = await self.docker._query_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 323, in _query_json
    async with self._query(
               ^^^^^^^^^^^^
  File "/home/jopemachine/.pyenv/versions/3.12.6/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 232, in _query
    yield await self._do_query(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/aiodocker/docker.py", line 298, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
aiodocker.exceptions.DockerError: DockerError(404, 'No such image: 192.168.0.112/test-project/e3e32:0.2')
```

### To Reproduce

Attempt to create a session with the image under these conditions.

- The image is not installed locally.
- The image does not have the `ai.backend.base-distro` label.
- The distro must not be cached in Redis.

### Expected Behavior

Pull the image from the registry and then create a session.

### Anything else?

None

**Comment by Ye123459** [comment]
According to the information you provide, the problem is that the resolve_image_distro() method tries to create a container with an unpulled image under some conditions. Specifically, init_kernel_context() is called before pull_image(), causing an attempt to create a container without the image being pulled, raising a DockerError(404, 'No such image:... ') Error.

To solve this problem, adjust the order of image pull and container initialization in the create_kernel() method to ensure that the image is pulled before the container is initialized. Here are the specific solutions:

Adjust the call order in the create_kernel() method:

Call pull_image() before init_kernel_context() to make sure the image is pulled.
Add image pull logic:

Add logic to the create_kernel() method to check if the image already exists. If it does not exist, pull the image first.

Here is an example of the modified code:
class Agent:
    async def create_kernel(self, kernel_config):
        try:
            await self.pull_image(kernel_config["image"])
            
            ctx = await self.init_kernel_context(kernel_config)
            
            return ctx
        except Exception as e:
            raise e

    async def pull_image(self, image_name):
        try:
            images = await self.docker.images.list()
            image_tags = [img['RepoTags'][0] for img in images if 'RepoTags' in img]
            if image_name not in image_tags:
                await self.docker.images.pull(image_name)
        except Exception as e:
            raise e

    async def init_kernel_context(self, kernel_config):
        try:
            distro = await self.resolve_image_distro(kernel_config["image"])
            return distro
        except Exception as e:
            raise e

    async def resolve_image_distro(self, image_name):
        try:
            container_config = {
                'image': image_name,
            }
            container = await self.docker.containers.create(container_config)
            return container
        except Exception as e:
            raise e

The above changes ensure that the image is pulled before initializing the kernel context, thus avoiding DockerError(404, 'No such image:... ') Error.

**Comment by jopemachine** [comment]
Closed duet to this is resolved in #2721.
