### ISSUE TITLE
After Docker containers creating a session, backend.ai agents don't get container information & shows 500 internal error

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#336]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

After backend.ai run, Docker containers are not available, backend.ai agents don't get container information.
Also web ui only shows 500 internal error
Backend.ai 실행시, 도커 컨테이너가 실행이 안되어, agent가 컨테이너의 정보를 가져오지 못함
또한 web-ui는 500 internal error메세지만 보여줌.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. run backend.ai manager
2. run backend.ai agent
3. run backend.ai proxy
4. run backend.ai webserver
4. run backend.ai 
```
backend.ai run python -c "print('hello world')"
∙ Session name prefix: pysdk-cf5ec2f8a6
```
(and then pending status)

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

```
backend.ai run python -c "print('hello world')"
∙ Session name prefix: pysdk-cf5ec2f8a6
hello world
```

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.

web ui message

<img width="1680" alt="스크린샷 2022-01-04 오후 2 39 11" src="https://user-images.githubusercontent.com/20002/148019496-72badebc-cb64-49ae-9b80-190165bc2d36.png">
<img width="1371" alt="스크린샷 2022-01-04 오후 3 45 47 1" src="https://user-images.githubusercontent.com/20002/148019924-9cd45e78-ed1b-4187-b86e-fbce2fcc2279.png">

console message
```
2022-01-04 14:43:08.607 INFO aiohttp.access [36391] 127.0.0.1 [04/Jan/2022:05:43:08 +0000] "POST /admin/graphql HTTP/1.1" 200 2395 "-" "Backend.AI Web Server 22.03.0-dev.2"
2022-01-04 14:43:08.635 DEBUG ai.backend.manager.plugin.error_monitor [36391] collected an error log [ERROR] "TypeError: expected str, got: None" from manager
2022-01-04 14:43:08.635 ERROR __main__ [36391] Uncaught exception in HTTP request handlers TypeError('expected str, got: None')
Traceback (most recent call last):
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 203, in exception_middleware
    resp = (await handler(request))
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 191, in api_middleware
    resp = (await _handler(request))
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/auth.py", line 523, in auth_middleware
    return (await handler(request))
  File "/usr/local/lib/python3.9/site-packages/aiotools/func.py", line 22, in wrapped
    return await coro(*args, *cargs, **kwargs, **ckwargs)
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/ratelimit.py", line 75, in rlim_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/manager.py", line 71, in wrapped
    return (await handler(request, *args, **kwargs))
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/auth.py", line 531, in wrapped
    return (await handler(request, *args, **kwargs))
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/utils.py", line 126, in wrapped
    return await handler(request, checked_params, *args, **kwargs)
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/api/session.py", line 1988, in get_container_logs
    resp['result']['logs'] = await registry.get_logs_from_agent(session_name, owner_access_key)
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 2198, in get_logs_from_agent
    async with RPCContext(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/Users/dhsung/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 216, in RPCContext
    async with peer:
  File "/usr/local/lib/python3.9/site-packages/callosum/rpc/channel.py", line 241, in __aenter__
    self._connection = await _opener.__aenter__()
  File "/usr/local/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 349, in __aenter__
    client_sock.connect(self.addr.uri)
  File "/usr/local/lib/python3.9/site-packages/zmq/sugar/socket.py", line 194, in connect
    super().connect(addr)
  File "zmq/backend/cython/socket.pyx", line 567, in zmq.backend.cython.socket.Socket.connect
TypeError: expected str, got: None
```

가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

**Client:**
 - OS: macOS Big Sur 11.6.1
 - App version: 21.09.2.211109
 - Browser version: Chrome 버전 96.0.4664.110(공식 빌드) (x86_64)
 - Python version: 3.9.9
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: [e.g. Ubuntu 18.04, CentOS 7.6, macOS 10.14]
   - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`]
```
Darwin jihyunkcBookPro.office.lablup 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```
 - Backend.AI version: [e.g. 19.09.0]
 - Python version: 3.9.9
 - Installation method:   scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

related KB1037 read-only filesystem DockerError when creating a session

**Comment by achimnol** [comment]
Before agents are assigned for a session & before the container is created and started, any attempts to fetch container logs should *gracefully* fail instead of raising internal server error.

**Comment by achimnol** [comment]
It should be handled in the manager since only the manager knows the actual status of pending sessions.

**Comment by achimnol** [comment]
We have improved error handling on container creation failures. Please report this again with the latest version if happens again.
