### ISSUE TITLE
After jinja2 package version up, not working login and found AssertionError 

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#342]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

After aiohttp & jinja2 `2.11.2` version up, call login request, then shows 404 error  on '/func' request and 500 error on '/server/login'& found Assertion Error on webserver.

try to login then, GET Method `/func` is 404 & server log shows 
```
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "GET /func/ HTTP/1.1" 404 281 "-" "Backend.AI Client for Python 22.03.0.dev0"
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "GET /func/manager/announcement HTTP/1.1" 401 259 "-" "Backend.AI Client for Python 22.03.0.dev0"
2022-01-05 17:21:11 ERROR aiohttp.server [66215] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp_session/__init__.py", line 198, in factory
    response = await handler(request)
  File "/Users/dhsung/backend.ai-dev/webserver/src/ai/backend/web/server.py", line 359, in login_handler
    assert anon_api_config.is_anonymous
AssertionError
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "POST /server/login HTTP/1.1" 500 244 "-" "Backend.AI Client for Python 22.03.0.dev0"
``` 

I think, aiohttp version and jinja2( 2.11.2 to 3.0.1) version up. then, Only build & CI processes are pass, shows runtime error as a package dependency(?)
.
So, that error needs to debug backand.ai-webserver's server.py , Line 359
https://github.com/lablup/backend.ai-webserver/blob/main/src/ai/backend/web/server.py#L359

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. run {manager, agent, storage-proxy, webserver} server
2. access default login page http://localhost:8090/
3. try to login (enter id & password)
4. watch & found webserver log
```
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "GET /func/ HTTP/1.1" 404 281 "-" "Backend.AI Client for Python 22.03.0.dev0"
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "GET /func/manager/announcement HTTP/1.1" 401 259 "-" "Backend.AI Client for Python 22.03.0.dev0"
2022-01-05 17:21:11 ERROR aiohttp.server [66215] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp_session/__init__.py", line 198, in factory
    response = await handler(request)
  File "/Users/dhsung/backend.ai-dev/webserver/src/ai/backend/web/server.py", line 359, in login_handler
    assert anon_api_config.is_anonymous
AssertionError
2022-01-05 17:21:11 INFO aiohttp.access [66215] 127.0.0.1 [05/Jan/2022:08:21:11 +0000] "POST /server/login HTTP/1.1" 500 244 "-" "Backend.AI Client for Python 22.03.0.dev0"
``` 

In my opinion, assertion error is package dependency? so need to debug the server.py
https://github.com/lablup/backend.ai-webserver/blob/main/src/ai/backend/web/server.py#L359

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
not asset error 
pass the login and move to manage page. 

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

<img width="1258" alt="스크린샷 2022-01-04 오후 5 38 29" src="https://user-images.githubusercontent.com/20002/148193654-eb683b4e-c256-4692-b4be-92ccf6d3a73f.png">
<img width="1017" alt="스크린샷 2022-01-05 오전 11 17 29" src="https://user-images.githubusercontent.com/20002/148193674-de94c416-f3eb-48ce-88c1-516d8b2addd7.png">

**Client:**
 - OS:   macOS Big Sur 11.6.1(20G224)
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: Chrome version 96.0.4664.110(Official build) (x86_64)
 - Python version: 3.9.9
 - NodeJS version: -

**Server:**
 - OS: macOS Big Sur 11.6.1(20G224)
   - Output of `uname -a`: `Darwin jihyunkcBookPro.office.lablup 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64`
 - Backend.AI version: 22.03.0.dev0
 - Python version: 3.9.9
 - Installation method:  used scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by achimnol** [comment]
The issue is proven to be a combination of configuration issues, including mix of environment variables across different Backend.AI component virtualenvs and a faulty reset procedure of the laptop (macOS data partition locking issue). Now @studioego can run the Backend.AI dev setup locally without this kind of issues.
