### ISSUE TITLE
Found the zeromq issue when run manage & agent using install-dev.sh on Ubuntu arm64 version

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#376]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

Finished installing backend.ai using `install-dev.sh` on Ubuntu arm64 platform, run manager task.

After running the backend.ai manager, shows an error message
```
(venv-pzb6tclh-manager) ubuntu@ip-10-122-1-234:~/backend.ai-dev/manager$ python -m ai.backend.manager.server --debug
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 75, in <module>
    from .registry import AgentRegistry
  File "/home/ubuntu/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 40, in <module>
    from callosum.lower.zeromq import ZeroMQAddress, ZeroMQRPCTransport
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-manager/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 176, in <module>
    class ZeroMQMonitorMixin:
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-manager/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 194, in ZeroMQMonitorMixin
    zmq.EVENT_HANDSHAKE_FAILED_AUTH: "handshake-faield-auth",
AttributeError: module 'zmq' has no attribute 'EVENT_HANDSHAKE_FAILED_AUTH'
(venv-pzb6tclh-manager) ubuntu@ip-10-122-1-234:~/backend.ai-dev/manager$
```

Also, running the backend.ai agent, shows an error message
```
(venv-pzb6tclh-agent) ubuntu@ip-10-122-1-234:~/backend.ai-dev/agent$ python -m ai.backend.agent.server --debug
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/backend.ai-dev/agent/src/ai/backend/agent/server.py", line 35, in <module>
    from callosum.lower.zeromq import ZeroMQAddress, ZeroMQRPCTransport
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-agent/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 176, in <module>
    class ZeroMQMonitorMixin:
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-agent/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 194, in ZeroMQMonitorMixin
    zmq.EVENT_HANDSHAKE_FAILED_AUTH: "handshake-faield-auth",
AttributeError: module 'zmq' has no attribute 'EVENT_HANDSHAKE_FAILED_AUTH'
(venv-pzb6tclh-agent) ubuntu@ip-10-122-1-234:~/backend.ai-dev/agent$ 
```

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1.  Install backend.ai using `install-dev.sh` on Ubuntu 20.04 LTS version
2. run backend.ai manager & agent
  - run backend.ai manager `python -m ai.backend.manager.server --debug`
  - run backend.ai agent `python -m ai.backend.agent.server --debug`

```
(venv-pzb6tclh-manager) ubuntu@ip-10-122-1-234:~/backend.ai-dev/manager$ python -m ai.backend.manager.server --debug
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 75, in <module>
    from .registry import AgentRegistry
  File "/home/ubuntu/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 40, in <module>
    from callosum.lower.zeromq import ZeroMQAddress, ZeroMQRPCTransport
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-manager/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 176, in <module>
    class ZeroMQMonitorMixin:
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-manager/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 194, in ZeroMQMonitorMixin
    zmq.EVENT_HANDSHAKE_FAILED_AUTH: "handshake-faield-auth",
AttributeError: module 'zmq' has no attribute 'EVENT_HANDSHAKE_FAILED_AUTH'
(venv-pzb6tclh-manager) ubuntu@ip-10-122-1-234:~/backend.ai-dev/manager$
```

Also, running the backend.ai agent, shows an error message
```
(venv-pzb6tclh-agent) ubuntu@ip-10-122-1-234:~/backend.ai-dev/agent$ python -m ai.backend.agent.server --debug
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/backend.ai-dev/agent/src/ai/backend/agent/server.py", line 35, in <module>
    from callosum.lower.zeromq import ZeroMQAddress, ZeroMQRPCTransport
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-agent/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 176, in <module>
    class ZeroMQMonitorMixin:
  File "/home/ubuntu/.pyenv/versions/venv-pzb6tclh-agent/lib/python3.9/site-packages/callosum/lower/zeromq.py", line 194, in ZeroMQMonitorMixin
    zmq.EVENT_HANDSHAKE_FAILED_AUTH: "handshake-faield-auth",
AttributeError: module 'zmq' has no attribute 'EVENT_HANDSHAKE_FAILED_AUTH'
(venv-pzb6tclh-agent) ubuntu@ip-10-122-1-234:~/backend.ai-dev/agent$ 
```

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

Normally run backend.ai manager & agent 

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/20002/154229422-54261132-148f-48c6-8fc8-7335c40e28ab.png">

**Server:**
 - OS: Ubuntu 20.04 LTS arm64 version 
   - Output of `uname -a`: `Linux ip-10-122-1-234 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:04:48 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
 - Backend.AI version: `main`
 - Python version: `3.9.10`
 - Installation method: used scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

Only shows the bug on Ubuntu ARM64 version (Don't watching Ubuntu x86_64 versino)

**Comment by studioego** [comment]
Ubuntu 20.04 LTS ARM version's libzmq version is 3.

However, pyzmq is binding libzmq4 version.

Hmm, It needs to compile libzmq4 or install libzmq4 custom package.
```
(venv-bh1g3y6i-manager) dhsung@dhsung-ubuntu:~/backend.ai-dev/manager$ python
Python 3.9.10 (main, Feb 15 2022, 08:09:46) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> zmq.__version__
'22.1.0'
>>> zmq.zmq_version()
'4.1.4'
>>> quit()
(venv-bh1g3y6i-manager) dhsung@dhsung-ubuntu:~/backend.ai-dev/manager$ sudo apt search zeromq
Sorting... Done
Full Text Search... Done
condure/impish 1.1.0-1 arm64
  HTTP/WebSocket connection manager

libczmq-dev/impish 4.2.1-1 arm64
  High-level C binding for ZeroMQ (development files)

libczmq4/impish 4.2.1-1 arm64
  High-level C binding for ZeroMQ

libghc-zeromq4-haskell-dev/impish 0.8.0-1build2 arm64
  bindings to ZeroMQ 4.x

libghc-zeromq4-haskell-doc/impish 0.8.0-1build2 all
  bindings to ZeroMQ 4.x; documentation

libghc-zeromq4-haskell-prof/impish 0.8.0-1build2 arm64
  bindings to ZeroMQ 4.x; profiling libraries

libgnuradio-zeromq3.8.2/impish 3.8.2.0-14 arm64
  gnuradio zeromq functions

libignition-transport-dev/impish 8.0.0+dfsg-3build1 arm64
  Ignition Robotics transport Library - Development files

libignition-transport8-8/impish 8.0.0+dfsg-3build1 arm64
  Ignition Robotics Transport Library - Shared library

libjeromq-java/impish 0.3.6-1.1 all
  Java implementation of the ZeroMQ messaging library

libmessage-passing-zeromq-perl/impish 0.010-2 all
  input and output messages to ZeroMQ

librust-zmq-dev/impish 0.9.2-2 arm64
  High-level bindings to the zeromq library - Rust source code

librust-zmq-sys-dev/impish 0.11.0-2 arm64
  Low-level bindings to the zeromq library - Rust source code

libteamdctl0/impish 1.31-1build1 arm64
  library for communication with `teamd` process

libzmq-ffi-perl/impish 1.17-2 all
  version agnostic Perl bindings for zeromq using ffi

libzmq-java/impish 3.1.0-15.1build1 arm64
  ZeroMQ Java bindings (jzmq)

libzmq-java-doc/impish 3.1.0-15.1build1 all
  Documentation for ZeroMQ Java bindings (jzmq)

libzmq-jni/impish 3.1.0-15.1build1 arm64
  ZeroMQ Java bindings (jzmq)

libzmq3-dev/impish,now 4.3.4-1 arm64 [installed]
  lightweight messaging kernel (development files)

octave-zeromq/impish 1.5.2-1build1 arm64
  ZeroMQ binding for Octave

php-zmq/impish 1.1.3-14build2 arm64
  ZeroMQ messaging bindings for PHP

python3-aiozmq/impish 0.9.0-1 all
  ZeroMQ integration with asyncio

python3-txzmq/impish 0.8.0-2 all
  ZeroMQ binding for the Twisted framework (Python3 version)

r-cran-pbdzmq/impish 0.3.5+dfsg-1 arm64
  R bindings for ZeroMQ from the pbdR project

rsyslog-czmq/impish 8.2102.0-2ubuntu2 arm64
  ZeroMQ protocol support for rsyslog via CZMQ

ruby-ffi-rzmq/impish 2.0.7-1 all
  FFI based Ruby bindings for ZeroMQ (ØMQ) networking library

ruby-ffi-rzmq-core/impish 1.0.7-1 all
  FFI wrapper around the ZeromMQ (ØMQ) networking library for Ruby

uwsgi-core/impish 2.0.19.1-7.1build1 arm64
  fast, self-healing application container server (core)

zurl/impish 1.11.0-2 arm64
  HTTP client worker with ZeroMQ interface

(venv-bh1g3y6i-manager) dhsung@dhsung-ubuntu:~/backend.ai-dev/manager$
```

**Comment by studioego** [comment]
In contrast, Ubuntu x86_64 & Mac use zeromq `4.3.4` version

**Ubuntu 20.04 LTS x86_64**
```
(venv-7eb2rsyv-manager) ubuntu@ip-10-122-3-254:~/backend.ai-dev/manager$ python 
Python 3.9.10 (main, Feb 16 2022, 05:38:17) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> zmq.__version__'22.1.0'
>>> zmq.zmq_version()
'4.3.4'
>>> 
```

**Mac**
```
Python 3.9.10 (main, Feb  5 2022, 16:35:18) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> zmq.__version__
'22.3.0'
>>> zmq.zmq_version()
'4.3.4'
>>>
```

**Comment by achimnol** [comment]
This is due to this line:
https://github.com/zeromq/pyzmq/blob/main/.github/workflows/wheels.yml#L218-L224

According to [zeromq/pyzmq#1602 comment](https://github.com/zeromq/pyzmq/issues/1602#issuecomment-908224148), we could apply the technique to dynamically define the zeromq event constants in [Callosum.lower.zeromq](https://github.com/lablup/callosum/blob/main/src/callosum/lower/zeromq.py#L194).
