### ISSUE TITLE
[Ubuntu 22.04] When Python is installed by default but pip package is not installed. Do need to add the python3-pip package on the script?

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#444]
[Ubuntu 22.04] When Python is installed by default but pip package is not installed. Do need to add the python3-pip package on the script?

**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

After installing Ubuntu 22.04 as a minimal installation method, I try to install backend.ai using pants. 

I checked the following error message while installing backend.ai.
```
/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "/home/dhsung/backend.ai/scripts/check-docker.py", line 10, in <module>
    import requests_unixsocket
ModuleNotFoundError: No module named 'requests_unixsocket'
dhsung@dhsung-QEMU-Virtual-Machine:~/backend.ai$ pip
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
```

The message shows to need to install the python3-pip package for Ubuntu on install-dev.sh script

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. install Ubuntu 22.04 minimal installation
2. clone backend.ai git repository
3. git clone backend.ai
4. try to install backend.ai using `install-dev.sh`
5. See error

```
/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "/home/dhsung/backend.ai/scripts/check-docker.py", line 10, in <module>
    import requests_unixsocket
ModuleNotFoundError: No module named 'requests_unixsocket'
dhsung@dhsung-QEMU-Virtual-Machine:~/backend.ai$ pip
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
```

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/20002/172418187-1d126666-e5ec-4263-915f-2e37a654329e.png">

**Server:**
 - OS:  Ubuntu 22.04  
   - Output of `uname -a`: Linux dhsung-QEMU-Virtual-Machine 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:57:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
 - Backend.AI version: 22.09 (in-dev)
 - Python version: Python 3.10.4
 - Installation method: Used scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

It's Ubuntu 22.04 LTS minimal  install version's issue.

**Comment by studioego** [comment]
According to @achimnol, He said that it would be better to write the pip installation in the prerequisite part of the manual `docs/install/development-setup.rst`. Depending on the environment, python3 itself may not be installed as a package.

**Comment by studioego** [comment]
If you regist the pyenv environment  on .bashrc 
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
However, On Ubuntu 22.04 environment, It don't understand python path, needs to regist pyenv's global regist version.
```
 pyenv global 3.10.4
```
<img width="740" alt="image" src="https://user-images.githubusercontent.com/20002/172549003-36add72f-97d7-4e0f-b7f7-020c7e267536.png">


<img width="756" alt="image" src="https://user-images.githubusercontent.com/20002/172549110-0ea69829-c5c1-408a-a367-8116b20ce524.png">

**Comment by studioego** [comment]
Also, If you install pants system, You need to install python 3.9 version (At that time 3.9.13 is current version.)
```
pyenv install 3.9.13
pyenv global 3.9.13
```

install rust following the install link https://rustup.rs/
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by studioego** [comment]
Fedora Core 35
```
pyenv install 3.9.12
pyenv global 3.9.12
```

install docker on Fedora Core 35
```
 curl -fsSL https://get.docker.com -o get-docker.sh=
 sudo sh get-docker.sh
```
If you watch the log 
```
Please install Rustup and ensure `rustup` is on your PATH (usually by adding ~/.cargo/bin). See https://rustup.rs.
```
should be install rust 
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env

```

**Comment by studioego** [comment]
need to add to require `python3-pip` package on Ubuntu or Fedora core & CentOS. 
So, I re-open the issue
