### ISSUE TITLE
'ImageRow' object has no attribute 'installed'

### ISSUE THREAD

**Issue by rapsealk** [lablup/backend.ai#930]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

22.09.6

### Describe the bug

Trying to list installed images, I faced an error:
```bash
2022-12-15 12:24:12.090 ERROR ai.backend.manager.cli.image_impl [20709] An error occurred.
Traceback (most recent call last):
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/manager/cli/image_impl.py", line 54, in list_images
    if installed and not item.installed:
AttributeError: 'ImageRow' object has no attribute 'installed'
```

It tries to access the `installed` field of an `ImageRow` object,
https://github.com/lablup/backend.ai/blob/174b844e5c8bb321157027d9efbff45d6a329642/src/ai/backend/manager/cli/image_impl.py#L50-L54

but `ImageRow` has no attribute/property named 'installed'.
https://github.com/lablup/backend.ai/blob/174b844e5c8bb321157027d9efbff45d6a329642/src/ai/backend/manager/models/image.py#L157-L193

### To Reproduce

```bash
% ./backend.ai mgr image list --installed

2022-12-15 12:24:12.090 ERROR ai.backend.manager.cli.image_impl [20709] An error occurred.
Traceback (most recent call last):
  File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/manager/cli/image_impl.py", line 54, in list_images
    if installed and not item.installed:
AttributeError: 'ImageRow' object has no attribute 'installed'
```

**Comment by rapsealk** [comment]
We may just prevent error by replacing
https://github.com/lablup/backend.ai/blob/174b844e5c8bb321157027d9efbff45d6a329642/src/ai/backend/manager/cli/image_impl.py#L54-L55
with
```python
        if installed and not (hasattr(item, "installed") and item.installed):
            log.warning("NOTE: installed/installed_agents fields are no longer provided in CLI, until we finish the epic refactoring of image metadata db.")
            return
```
